### ISSUE TITLE
Is it possible to give this app as splunk downloadables as this is not available in splunkbase

### ISSUE THREAD

**Issue by Divyagn92** [aholzel/TA-dmarc#3]
we are not able to download this app in splunkbase, so is it possible to provide the steps to get this app in downloadable format to install this app in our environment

**Comment by aholzel** [comment]
Just click the download button on the "<> Code" page and choose "download zip" just note that the folder inside the zip is called "TA-dmarc-master" so you need to change that to TA-dmarc
