### ISSUE TITLE
New MS DMARC aggregation reports not processed

### ISSUE THREAD

**Issue by jbouwh** [aholzel/TA-dmarc#8]
Microsoft started sending aggregation reports with sibjects like:
[Preview] Report Domain: example.com Submitter: protection.outlook.com Report-ID: 9ab4470a418d4e94ba721daea59xxxxx

The prefix `[Preview]` causes these reports not to be processed.

**Comment by aholzel** [comment]
Thanks for reporting! Good to see that microsoft is finally sending out reports... I fixed this in version 4.0.1
